// ================== DANH MỤC THỂ LOẠI ==================
export const CATEGORIES = [
    { key: 'tu-tien', name: 'Tu Tiên' },
    { key: 'luyen-cap', name: 'Luyện Cấp' },
    { key: 'trung-sinh', name: 'Trùng Sinh' },
    { key: 'kiem-hiep', name: 'Kiếm Hiệp' },
    { key: 'xuyen-khong', name: 'Xuyên Không' },
];

// Helper: chuyển mảng link -> [{ep, title, url}]
const mapEpisodes = (links) => links.map((url, i) => ({ ep: i + 1, title: `Tập ${i + 1}`, url }));

// ================== DỮ LIỆU THỦ CÔNG ==================
// Quy ước ảnh bìa: /public/film-posters/<thể-loại>/<1..5>.jpg
// Mỗi phim có cả bộ trường theo yêu cầu và các khóa cũ cho app.
export const FILMS = {
    // ---------------- TU TIÊN ----------------
    'tu-tien': [
        {
            id: 'tu-tien-1',
            category: 'tu-tien',
            slug: 'tu-tien-1',
            title: 'Tu Tiên 1',
            'ten-phim': 'Tu Tiên 1',
            cover: '/film-posters/tu-tien/1.jpg',
            poster: '/film-posters/tu-tien/1.jpg',
            'mo-ta': 'Con đường tu đạo đầy thử thách mở ra trước mắt thiếu niên có linh căn kỳ lạ.',
            description: 'Con đường tu đạo đầy thử thách mở ra trước mắt thiếu niên có linh căn kỳ lạ.',
            'so-tap': 16,
            duration: '20 phút',
            tags: ['Tu Tiên'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=10s',
                'https://www.youtube.com/watch?v=6PUExe3wFxQ',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=70s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=100s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=130s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=160s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=190s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=220s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=250s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=280s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=310s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=340s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=370s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=400s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=430s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=430s',

            ]),
        },
        {
            id: 'tu-tien-2',
            category: 'tu-tien',
            slug: 'tu-tien-2',
            title: 'Tu Tiên 2',
            'ten-phim': 'Tu Tiên 2',
            cover: '/film-posters/tu-tien/2.jpg',
            poster: '/film-posters/tu-tien/2.jpg',
            'mo-ta': 'Thiếu hiệp bước vào bí cảnh, tranh đoạt truyền thừa cổ.',
            description: 'Thiếu hiệp bước vào bí cảnh, tranh đoạt truyền thừa cổ.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Tu Tiên'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=10s',
                'https://www.youtube.com/watch?v=6PUExe3wFxQ',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=70s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=100s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=130s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=160s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=190s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=220s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=250s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=280s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=310s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=340s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=370s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=400s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=430s',
                'https://www.youtube.com/watch?v=dk7YWiQcn08&t=430s',

            ]),
        },
        {
            id: 'tu-tien-3',
            category: 'tu-tien',
            slug: 'tu-tien-3',
            title: 'Tu Tiên 3',
            'ten-phim': 'Tu Tiên 3',
            cover: '/film-posters/tu-tien/3.jpg',
            poster: '/film-posters/tu-tien/3.jpg',
            'mo-ta': 'Đại hội tông môn, tranh bá thiên hạ tu chân.',
            description: 'Đại hội tông môn, tranh bá thiên hạ tu chân.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Tu Tiên'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=aqz-KE-bpKQ&t=5s',
                'https://www.youtube.com/watch?v=aqz-KE-bpKQ&t=35s',
                'https://www.youtube.com/watch?v=aqz-KE-bpKQ&t=65s',
                'https://www.youtube.com/watch?v=aqz-KE-bpKQ&t=95s',
                'https://www.youtube.com/watch?v=aqz-KE-bpKQ&t=125s',
                'https://www.youtube.com/watch?v=aqz-KE-bpKQ&t=155s',
                'https://www.youtube.com/watch?v=aqz-KE-bpKQ&t=185s',
                'https://www.youtube.com/watch?v=aqz-KE-bpKQ&t=215s',
                'https://www.youtube.com/watch?v=aqz-KE-bpKQ&t=245s',
                'https://www.youtube.com/watch?v=aqz-KE-bpKQ&t=275s',
                'https://www.youtube.com/watch?v=aqz-KE-bpKQ&t=305s',
                'https://www.youtube.com/watch?v=aqz-KE-bpKQ&t=335s',
                'https://www.youtube.com/watch?v=aqz-KE-bpKQ&t=365s',
                'https://www.youtube.com/watch?v=aqz-KE-bpKQ&t=395s',
                'https://www.youtube.com/watch?v=aqz-KE-bpKQ&t=425s',
            ]),
        },
        {
            id: 'tu-tien-4',
            category: 'tu-tien',
            slug: 'tu-tien-4',
            title: 'Tu Tiên 4',
            'ten-phim': 'Tu Tiên 4',
            cover: '/film-posters/tu-tien/4.jpg',
            poster: '/film-posters/tu-tien/4.jpg',
            'mo-ta': 'Khai mở bí mật về linh dược vạn năm và ma chủng.',
            description: 'Khai mở bí mật về linh dược vạn năm và ma chủng.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Tu Tiên'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=ScMzIvxBSi4&t=10s',
                'https://www.youtube.com/watch?v=ScMzIvxBSi4&t=40s',
                'https://www.youtube.com/watch?v=ScMzIvxBSi4&t=70s',
                'https://www.youtube.com/watch?v=ScMzIvxBSi4&t=100s',
                'https://www.youtube.com/watch?v=ScMzIvxBSi4&t=130s',
                'https://www.youtube.com/watch?v=ScMzIvxBSi4&t=160s',
                'https://www.youtube.com/watch?v=ScMzIvxBSi4&t=190s',
                'https://www.youtube.com/watch?v=ScMzIvxBSi4&t=220s',
                'https://www.youtube.com/watch?v=ScMzIvxBSi4&t=250s',
                'https://www.youtube.com/watch?v=ScMzIvxBSi4&t=280s',
                'https://www.youtube.com/watch?v=ScMzIvxBSi4&t=310s',
                'https://www.youtube.com/watch?v=ScMzIvxBSi4&t=340s',
                'https://www.youtube.com/watch?v=ScMzIvxBSi4&t=370s',
                'https://www.youtube.com/watch?v=ScMzIvxBSi4&t=400s',
                'https://www.youtube.com/watch?v=ScMzIvxBSi4&t=430s',
            ]),
        },
        {
            id: 'tu-tien-5',
            category: 'tu-tien',
            slug: 'tu-tien-5',
            title: 'Tu Tiên 5',
            'ten-phim': 'Tu Tiên 5',
            cover: '/film-posters/tu-tien/5.jpg',
            poster: '/film-posters/tu-tien/5.jpg',
            'mo-ta': 'Hồn thiên cổ giới và trận chiến phong ấn yêu ma.',
            description: 'Hồn thiên cổ giới và trận chiến phong ấn yêu ma.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Tu Tiên'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=15s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=45s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=75s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=105s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=135s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=165s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=195s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=225s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=255s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=285s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=315s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=345s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=375s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=405s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=435s',
            ]),
        },
        {
            id: 'tu-tien-6',
            category: 'tu-tien',
            slug: 'tu-tien-6',
            title: 'Tu Tiên 6',
            'ten-phim': 'Tu Tiên 6',
            cover: '/film-posters/tu-tien/6.jpg',
            poster: '/film-posters/tu-tien/6.jpg',
            'mo-ta': 'Hồn thiên cổ giới và trận chiến phong ấn yêu ma.',
            description: 'Hồn thiên cổ giới và trận chiến phong ấn yêu ma.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Tu Tiên'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=15s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=45s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=75s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=105s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=135s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=165s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=195s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=225s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=255s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=285s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=315s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=345s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=375s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=405s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=435s',
            ]),
        },
        {
            id: 'tu-tien-7',
            category: 'tu-tien',
            slug: 'tu-tien-7',
            title: 'Tu Tiên 7',
            'ten-phim': 'Tu Tiên 7',
            cover: '/film-posters/tu-tien/7.jpg',
            poster: '/film-posters/tu-tien/7.jpg',
            'mo-ta': 'Hồn thiên cổ giới và trận chiến phong ấn yêu ma.',
            description: 'Hồn thiên cổ giới và trận chiến phong ấn yêu ma.',
            'so-tap': 16,
            duration: '20 phút',
            tags: ['Tu Tiên'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=15s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=45s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=75s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=105s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=135s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=165s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=195s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=225s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=255s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=285s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=315s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=345s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=375s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=405s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=435s',
                'https://www.youtube.com/watch?v=jfKfPfyJRdk&t=435s',
            ]),
        },

    ],

    // ---------------- LUYỆN CẤP ----------------
    'luyen-cap': [
        {
            id: 'luyen-cap-1',
            category: 'luyen-cap',
            slug: 'luyen-cap-1',
            title: 'Luyện Cấp 1',
            'ten-phim': 'Luyện Cấp 1',
            cover: '/film-posters/luyen-cap/1.jpg',
            poster: '/film-posters/luyen-cap/1.jpg',
            'mo-ta': 'Tân thủ bước vào phó bản đầu tiên, học cách cộng điểm và khảm ngọc.',
            description: 'Tân thủ bước vào phó bản đầu tiên, học cách cộng điểm và khảm ngọc.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Luyện Cấp'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=2Vv-BfVoq4g&t=10s',
                'https://www.youtube.com/watch?v=2Vv-BfVoq4g&t=40s',
                'https://www.youtube.com/watch?v=2Vv-BfVoq4g&t=70s',
                'https://www.youtube.com/watch?v=2Vv-BfVoq4g&t=100s',
                'https://www.youtube.com/watch?v=2Vv-BfVoq4g&t=130s',
                'https://www.youtube.com/watch?v=2Vv-BfVoq4g&t=160s',
                'https://www.youtube.com/watch?v=2Vv-BfVoq4g&t=190s',
                'https://www.youtube.com/watch?v=2Vv-BfVoq4g&t=220s',
                'https://www.youtube.com/watch?v=2Vv-BfVoq4g&t=250s',
                'https://www.youtube.com/watch?v=2Vv-BfVoq4g&t=280s',
                'https://www.youtube.com/watch?v=2Vv-BfVoq4g&t=310s',
                'https://www.youtube.com/watch?v=2Vv-BfVoq4g&t=340s',
                'https://www.youtube.com/watch?v=2Vv-BfVoq4g&t=370s',
                'https://www.youtube.com/watch?v=2Vv-BfVoq4g&t=400s',
                'https://www.youtube.com/watch?v=2Vv-BfVoq4g&t=430s',
            ]),
        },
        {
            id: 'luyen-cap-2',
            category: 'luyen-cap',
            slug: 'luyen-cap-2',
            title: 'Luyện Cấp 2',
            'ten-phim': 'Luyện Cấp 2',
            cover: '/film-posters/luyen-cap/2.jpg',
            poster: '/film-posters/luyen-cap/2.jpg',
            'mo-ta': 'Tổ đội săn boss thế giới, rớt vật phẩm truyền thuyết.',
            description: 'Tổ đội săn boss thế giới, rớt vật phẩm truyền thuyết.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Luyện Cấp'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=3JZ_D3ELwOQ&t=5s',
                'https://www.youtube.com/watch?v=3JZ_D3ELwOQ&t=35s',
                'https://www.youtube.com/watch?v=3JZ_D3ELwOQ&t=65s',
                'https://www.youtube.com/watch?v=3JZ_D3ELwOQ&t=95s',
                'https://www.youtube.com/watch?v=3JZ_D3ELwOQ&t=125s',
                'https://www.youtube.com/watch?v=3JZ_D3ELwOQ&t=155s',
                'https://www.youtube.com/watch?v=3JZ_D3ELwOQ&t=185s',
                'https://www.youtube.com/watch?v=3JZ_D3ELwOQ&t=215s',
                'https://www.youtube.com/watch?v=3JZ_D3ELwOQ&t=245s',
                'https://www.youtube.com/watch?v=3JZ_D3ELwOQ&t=275s',
                'https://www.youtube.com/watch?v=3JZ_D3ELwOQ&t=305s',
                'https://www.youtube.com/watch?v=3JZ_D3ELwOQ&t=335s',
                'https://www.youtube.com/watch?v=3JZ_D3ELwOQ&t=365s',
                'https://www.youtube.com/watch?v=3JZ_D3ELwOQ&t=395s',
                'https://www.youtube.com/watch?v=3JZ_D3ELwOQ&t=425s',
            ]),
        },
        {
            id: 'luyen-cap-3',
            category: 'luyen-cap',
            slug: 'luyen-cap-3',
            title: 'Luyện Cấp 3',
            'ten-phim': 'Luyện Cấp 3',
            cover: '/film-posters/luyen-cap/3.jpg',
            poster: '/film-posters/luyen-cap/3.jpg',
            'mo-ta': 'Đấu trường liên server và bí kíp combo bất bại.',
            description: 'Đấu trường liên server và bí kíp combo bất bại.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Luyện Cấp'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=CevxZvSJLk8&t=10s',
                'https://www.youtube.com/watch?v=CevxZvSJLk8&t=40s',
                'https://www.youtube.com/watch?v=CevxZvSJLk8&t=70s',
                'https://www.youtube.com/watch?v=CevxZvSJLk8&t=100s',
                'https://www.youtube.com/watch?v=CevxZvSJLk8&t=130s',
                'https://www.youtube.com/watch?v=CevxZvSJLk8&t=160s',
                'https://www.youtube.com/watch?v=CevxZvSJLk8&t=190s',
                'https://www.youtube.com/watch?v=CevxZvSJLk8&t=220s',
                'https://www.youtube.com/watch?v=CevxZvSJLk8&t=250s',
                'https://www.youtube.com/watch?v=CevxZvSJLk8&t=280s',
                'https://www.youtube.com/watch?v=CevxZvSJLk8&t=310s',
                'https://www.youtube.com/watch?v=CevxZvSJLk8&t=340s',
                'https://www.youtube.com/watch?v=CevxZvSJLk8&t=370s',
                'https://www.youtube.com/watch?v=CevxZvSJLk8&t=400s',
                'https://www.youtube.com/watch?v=CevxZvSJLk8&t=430s',
            ]),
        },
        {
            id: 'luyen-cap-4',
            category: 'luyen-cap',
            slug: 'luyen-cap-4',
            title: 'Luyện Cấp 4',
            'ten-phim': 'Luyện Cấp 4',
            cover: '/film-posters/luyen-cap/4.jpg',
            poster: '/film-posters/luyen-cap/4.jpg',
            'mo-ta': 'Vượt tháp thử thách 100 tầng để thức tỉnh kỹ năng ẩn.',
            description: 'Vượt tháp thử thách 100 tầng để thức tỉnh kỹ năng ẩn.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Luyện Cấp'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=fRh_vgS2dFE&t=10s',
                'https://www.youtube.com/watch?v=fRh_vgS2dFE&t=40s',
                'https://www.youtube.com/watch?v=fRh_vgS2dFE&t=70s',
                'https://www.youtube.com/watch?v=fRh_vgS2dFE&t=100s',
                'https://www.youtube.com/watch?v=fRh_vgS2dFE&t=130s',
                'https://www.youtube.com/watch?v=fRh_vgS2dFE&t=160s',
                'https://www.youtube.com/watch?v=fRh_vgS2dFE&t=190s',
                'https://www.youtube.com/watch?v=fRh_vgS2dFE&t=220s',
                'https://www.youtube.com/watch?v=fRh_vgS2dFE&t=250s',
                'https://www.youtube.com/watch?v=fRh_vgS2dFE&t=280s',
                'https://www.youtube.com/watch?v=fRh_vgS2dFE&t=310s',
                'https://www.youtube.com/watch?v=fRh_vgS2dFE&t=340s',
                'https://www.youtube.com/watch?v=fRh_vgS2dFE&t=370s',
                'https://www.youtube.com/watch?v=fRh_vgS2dFE&t=400s',
                'https://www.youtube.com/watch?v=fRh_vgS2dFE&t=430s',
            ]),
        },
        {
            id: 'luyen-cap-5',
            category: 'luyen-cap',
            slug: 'luyen-cap-5',
            title: 'Luyện Cấp 5',
            'ten-phim': 'Luyện Cấp 5',
            cover: '/film-posters/luyen-cap/5.jpg',
            poster: '/film-posters/luyen-cap/5.jpg',
            'mo-ta': 'Tranh đoạt vương miện mùa giải và điểm danh dự.',
            description: 'Tranh đoạt vương miện mùa giải và điểm danh dự.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Luyện Cấp'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=10s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=40s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=70s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=100s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=130s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=160s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=190s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=220s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=250s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=280s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=310s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=340s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=370s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=400s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=430s',
            ]),
        },
        {
            id: 'luyen-cap-6',
            category: 'luyen-cap',
            slug: 'luyen-cap-6',
            title: 'Luyện Cấp 6',
            'ten-phim': 'Luyện Cấp 6',
            cover: '/film-posters/luyen-cap/6.jpg',
            poster: '/film-posters/luyen-cap/6.jpg',
            'mo-ta': 'Tranh đoạt vương miện mùa giải và điểm danh dự.',
            description: 'Tranh đoạt vương miện mùa giải và điểm danh dự.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Luyện Cấp'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=10s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=40s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=70s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=100s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=130s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=160s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=190s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=220s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=250s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=280s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=310s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=340s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=370s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=400s',
                'https://www.youtube.com/watch?v=OPf0YbXqDm0&t=430s',
            ]),
        },
    ],

    // ---------------- TRÙNG SINH ----------------
    'trung-sinh': [
        {
            id: 'trung-sinh-1',
            category: 'trung-sinh',
            slug: 'trung-sinh-1',
            title: 'Trùng Sinh 1',
            'ten-phim': 'Trùng Sinh 1',
            cover: '/film-posters/trung-sinh/1.jpg',
            poster: '/film-posters/trung-sinh/1.jpg',
            'mo-ta': 'Nhân vật chính trọng sinh về thời niên thiếu để thay đổi vận mệnh.',
            description: 'Nhân vật chính trọng sinh về thời niên thiếu để thay đổi vận mệnh.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Trùng Sinh'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=hTWKbfoikeg&t=10s',
                'https://www.youtube.com/watch?v=hTWKbfoikeg&t=40s',
                'https://www.youtube.com/watch?v=hTWKbfoikeg&t=70s',
                'https://www.youtube.com/watch?v=hTWKbfoikeg&t=100s',
                'https://www.youtube.com/watch?v=hTWKbfoikeg&t=130s',
                'https://www.youtube.com/watch?v=hTWKbfoikeg&t=160s',
                'https://www.youtube.com/watch?v=hTWKbfoikeg&t=190s',
                'https://www.youtube.com/watch?v=hTWKbfoikeg&t=220s',
                'https://www.youtube.com/watch?v=hTWKbfoikeg&t=250s',
                'https://www.youtube.com/watch?v=hTWKbfoikeg&t=280s',
                'https://www.youtube.com/watch?v=hTWKbfoikeg&t=310s',
                'https://www.youtube.com/watch?v=hTWKbfoikeg&t=340s',
                'https://www.youtube.com/watch?v=hTWKbfoikeg&t=370s',
                'https://www.youtube.com/watch?v=hTWKbfoikeg&t=400s',
                'https://www.youtube.com/watch?v=hTWKbfoikeg&t=430s',
            ]),
        },
        {
            id: 'trung-sinh-2',
            category: 'trung-sinh',
            slug: 'trung-sinh-2',
            title: 'Trùng Sinh 2',
            'ten-phim': 'Trùng Sinh 2',
            cover: '/film-posters/trung-sinh/2.jpg',
            poster: '/film-posters/trung-sinh/2.jpg',
            'mo-ta': 'Sử dụng ký ức tương lai để xây dựng đế chế mới.',
            description: 'Sử dụng ký ức tương lai để xây dựng đế chế mới.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Trùng Sinh'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=ktvTqknDobU&t=10s',
                'https://www.youtube.com/watch?v=ktvTqknDobU&t=40s',
                'https://www.youtube.com/watch?v=ktvTqknDobU&t=70s',
                'https://www.youtube.com/watch?v=ktvTqknDobU&t=100s',
                'https://www.youtube.com/watch?v=ktvTqknDobU&t=130s',
                'https://www.youtube.com/watch?v=ktvTqknDobU&t=160s',
                'https://www.youtube.com/watch?v=ktvTqknDobU&t=190s',
                'https://www.youtube.com/watch?v=ktvTqknDobU&t=220s',
                'https://www.youtube.com/watch?v=ktvTqknDobU&t=250s',
                'https://www.youtube.com/watch?v=ktvTqknDobU&t=280s',
                'https://www.youtube.com/watch?v=ktvTqknDobU&t=310s',
                'https://www.youtube.com/watch?v=ktvTqknDobU&t=340s',
                'https://www.youtube.com/watch?v=ktvTqknDobU&t=370s',
                'https://www.youtube.com/watch?v=ktvTqknDobU&t=400s',
                'https://www.youtube.com/watch?v=ktvTqknDobU&t=430s',
            ]),
        },
        {
            id: 'trung-sinh-3',
            category: 'trung-sinh',
            slug: 'trung-sinh-3',
            title: 'Trùng Sinh 3',
            'ten-phim': 'Trùng Sinh 3',
            cover: '/film-posters/trung-sinh/3.jpg',
            poster: '/film-posters/trung-sinh/3.jpg',
            'mo-ta': 'Hồi sinh trong thân xác khác và gặp lại cố nhân.',
            description: 'Hồi sinh trong thân xác khác và gặp lại cố nhân.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Trùng Sinh'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=LjhCEhWiKXk&t=10s',
                'https://www.youtube.com/watch?v=LjhCEhWiKXk&t=40s',
                'https://www.youtube.com/watch?v=LjhCEhWiKXk&t=70s',
                'https://www.youtube.com/watch?v=LjhCEhWiKXk&t=100s',
                'https://www.youtube.com/watch?v=LjhCEhWiKXk&t=130s',
                'https://www.youtube.com/watch?v=LjhCEhWiKXk&t=160s',
                'https://www.youtube.com/watch?v=LjhCEhWiKXk&t=190s',
                'https://www.youtube.com/watch?v=LjhCEhWiKXk&t=220s',
                'https://www.youtube.com/watch?v=LjhCEhWiKXk&t=250s',
                'https://www.youtube.com/watch?v=LjhCEhWiKXk&t=280s',
                'https://www.youtube.com/watch?v=LjhCEhWiKXk&t=310s',
                'https://www.youtube.com/watch?v=LjhCEhWiKXk&t=340s',
                'https://www.youtube.com/watch?v=LjhCEhWiKXk&t=370s',
                'https://www.youtube.com/watch?v=LjhCEhWiKXk&t=400s',
                'https://www.youtube.com/watch?v=LjhCEhWiKXk&t=430s',
            ]),
        },
        {
            id: 'trung-sinh-4',
            category: 'trung-sinh',
            slug: 'trung-sinh-4',
            title: 'Trùng Sinh 4',
            'ten-phim': 'Trùng Sinh 4',
            cover: '/film-posters/trung-sinh/4.jpg',
            poster: '/film-posters/trung-sinh/4.jpg',
            'mo-ta': 'Trở về trước đại nạn, thay đổi bánh xe lịch sử.',
            description: 'Trở về trước đại nạn, thay đổi bánh xe lịch sử.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Trùng Sinh'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=kXYiU_JCYtU&t=10s',
                'https://www.youtube.com/watch?v=kXYiU_JCYtU&t=40s',
                'https://www.youtube.com/watch?v=kXYiU_JCYtU&t=70s',
                'https://www.youtube.com/watch?v=kXYiU_JCYtU&t=100s',
                'https://www.youtube.com/watch?v=kXYiU_JCYtU&t=130s',
                'https://www.youtube.com/watch?v=kXYiU_JCYtU&t=160s',
                'https://www.youtube.com/watch?v=kXYiU_JCYtU&t=190s',
                'https://www.youtube.com/watch?v=kXYiU_JCYtU&t=220s',
                'https://www.youtube.com/watch?v=kXYiU_JCYtU&t=250s',
                'https://www.youtube.com/watch?v=kXYiU_JCYtU&t=280s',
                'https://www.youtube.com/watch?v=kXYiU_JCYtU&t=310s',
                'https://www.youtube.com/watch?v=kXYiU_JCYtU&t=340s',
                'https://www.youtube.com/watch?v=kXYiU_JCYtU&t=370s',
                'https://www.youtube.com/watch?v=kXYiU_JCYtU&t=400s',
                'https://www.youtube.com/watch?v=kXYiU_JCYtU&t=430s',
            ]),
        },
        {
            id: 'trung-sinh-5',
            category: 'trung-sinh',
            slug: 'trung-sinh-5',
            title: 'Trùng Sinh 5',
            'ten-phim': 'Trùng Sinh 5',
            cover: '/film-posters/trung-sinh/5.jpg',
            poster: '/film-posters/trung-sinh/5.jpg',
            'mo-ta': 'Vòng lặp thời gian và bí ẩn kẻ thao túng.',
            description: 'Vòng lặp thời gian và bí ẩn kẻ thao túng.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Trùng Sinh'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=10s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=40s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=70s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=100s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=130s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=160s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=190s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=220s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=250s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=280s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=310s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=340s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=370s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=400s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=430s',
            ]),
        },
        {
            id: 'trung-sinh-6',
            category: 'trung-sinh',
            slug: 'trung-sinh-6',
            title: 'Trùng Sinh 6',
            'ten-phim': 'Trùng Sinh 6',
            cover: '/film-posters/trung-sinh/6.jpg',
            poster: '/film-posters/trung-sinh/6.jpg',
            'mo-ta': 'Vòng lặp thời gian và bí ẩn kẻ thao túng.',
            description: 'Vòng lặp thời gian và bí ẩn kẻ thao túng.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Trùng Sinh'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=10s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=40s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=70s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=100s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=130s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=160s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=190s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=220s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=250s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=280s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=310s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=340s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=370s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=400s',
                'https://www.youtube.com/watch?v=09R8_2nJtjg&t=430s',
            ]),
        },
    ],

    // ---------------- KIẾM HIỆP ----------------
    'kiem-hiep': [
        {
            id: 'kiem-hiep-1',
            category: 'kiem-hiep',
            slug: 'kiem-hiep-1',
            title: 'Kiếm Hiệp 1',
            'ten-phim': 'Kiếm Hiệp 1',
            cover: '/film-posters/kiem-hiep/1.jpg',
            poster: '/film-posters/kiem-hiep/1.jpg',
            'mo-ta': 'Giang hồ dậy sóng với thần kiếm thất truyền.',
            description: 'Giang hồ dậy sóng với thần kiếm thất truyền.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Kiếm Hiệp'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=Zi_XLOBDo_Y&t=10s',
                'https://www.youtube.com/watch?v=Zi_XLOBDo_Y&t=40s',
                'https://www.youtube.com/watch?v=Zi_XLOBDo_Y&t=70s',
                'https://www.youtube.com/watch?v=Zi_XLOBDo_Y&t=100s',
                'https://www.youtube.com/watch?v=Zi_XLOBDo_Y&t=130s',
                'https://www.youtube.com/watch?v=Zi_XLOBDo_Y&t=160s',
                'https://www.youtube.com/watch?v=Zi_XLOBDo_Y&t=190s',
                'https://www.youtube.com/watch?v=Zi_XLOBDo_Y&t=220s',
                'https://www.youtube.com/watch?v=Zi_XLOBDo_Y&t=250s',
                'https://www.youtube.com/watch?v=Zi_XLOBDo_Y&t=280s',
                'https://www.youtube.com/watch?v=Zi_XLOBDo_Y&t=310s',
                'https://www.youtube.com/watch?v=Zi_XLOBDo_Y&t=340s',
                'https://www.youtube.com/watch?v=Zi_XLOBDo_Y&t=370s',
                'https://www.youtube.com/watch?v=Zi_XLOBDo_Y&t=400s',
                'https://www.youtube.com/watch?v=Zi_XLOBDo_Y&t=430s',
            ]),
        },
        {
            id: 'kiem-hiep-2',
            category: 'kiem-hiep',
            slug: 'kiem-hiep-2',
            title: 'Kiếm Hiệp 2',
            'ten-phim': 'Kiếm Hiệp 2',
            cover: '/film-posters/kiem-hiep/2.jpg',
            poster: '/film-posters/kiem-hiep/2.jpg',
            'mo-ta': 'Ân oán tình thù giữa hai đại môn phái.',
            description: 'Ân oán tình thù giữa hai đại môn phái.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Kiếm Hiệp'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=uelHwf8o7_U&t=10s',
                'https://www.youtube.com/watch?v=uelHwf8o7_U&t=40s',
                'https://www.youtube.com/watch?v=uelHwf8o7_U&t=70s',
                'https://www.youtube.com/watch?v=uelHwf8o7_U&t=100s',
                'https://www.youtube.com/watch?v=uelHwf8o7_U&t=130s',
                'https://www.youtube.com/watch?v=uelHwf8o7_U&t=160s',
                'https://www.youtube.com/watch?v=uelHwf8o7_U&t=190s',
                'https://www.youtube.com/watch?v=uelHwf8o7_U&t=220s',
                'https://www.youtube.com/watch?v=uelHwf8o7_U&t=250s',
                'https://www.youtube.com/watch?v=uelHwf8o7_U&t=280s',
                'https://www.youtube.com/watch?v=uelHwf8o7_U&t=310s',
                'https://www.youtube.com/watch?v=uelHwf8o7_U&t=340s',
                'https://www.youtube.com/watch?v=uelHwf8o7_U&t=370s',
                'https://www.youtube.com/watch?v=uelHwf8o7_U&t=400s',
                'https://www.youtube.com/watch?v=uelHwf8o7_U&t=430s',
            ]),
        },
        {
            id: 'kiem-hiep-3',
            category: 'kiem-hiep',
            slug: 'kiem-hiep-3',
            title: 'Kiếm Hiệp 3',
            'ten-phim': 'Kiếm Hiệp 3',
            cover: '/film-posters/kiem-hiep/3.jpg',
            poster: '/film-posters/kiem-hiep/3.jpg',
            'mo-ta': 'Thiếu hiệp và thanh kiếm sát thần.',
            description: 'Thiếu hiệp và thanh kiếm sát thần.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Kiếm Hiệp'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=SlPhMPnQ58k&t=10s',
                'https://www.youtube.com/watch?v=SlPhMPnQ58k&t=40s',
                'https://www.youtube.com/watch?v=SlPhMPnQ58k&t=70s',
                'https://www.youtube.com/watch?v=SlPhMPnQ58k&t=100s',
                'https://www.youtube.com/watch?v=SlPhMPnQ58k&t=130s',
                'https://www.youtube.com/watch?v=SlPhMPnQ58k&t=160s',
                'https://www.youtube.com/watch?v=SlPhMPnQ58k&t=190s',
                'https://www.youtube.com/watch?v=SlPhMPnQ58k&t=220s',
                'https://www.youtube.com/watch?v=SlPhMPnQ58k&t=250s',
                'https://www.youtube.com/watch?v=SlPhMPnQ58k&t=280s',
                'https://www.youtube.com/watch?v=SlPhMPnQ58k&t=310s',
                'https://www.youtube.com/watch?v=SlPhMPnQ58k&t=340s',
                'https://www.youtube.com/watch?v=SlPhMPnQ58k&t=370s',
                'https://www.youtube.com/watch?v=SlPhMPnQ58k&t=400s',
                'https://www.youtube.com/watch?v=SlPhMPnQ58k&t=430s',
            ]),
        },
        {
            id: 'kiem-hiep-4',
            category: 'kiem-hiep',
            slug: 'kiem-hiep-4',
            title: 'Kiếm Hiệp 4',
            'ten-phim': 'Kiếm Hiệp 4',
            cover: '/film-posters/kiem-hiep/4.jpg',
            poster: '/film-posters/kiem-hiep/4.jpg',
            'mo-ta': 'Lang bạt giang hồ, truy tìm bí kíp thất truyền.',
            description: 'Lang bạt giang hồ, truy tìm bí kíp thất truyền.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Kiếm Hiệp'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=60ItHLz5WEA&t=10s',
                'https://www.youtube.com/watch?v=60ItHLz5WEA&t=40s',
                'https://www.youtube.com/watch?v=60ItHLz5WEA&t=70s',
                'https://www.youtube.com/watch?v=60ItHLz5WEA&t=100s',
                'https://www.youtube.com/watch?v=60ItHLz5WEA&t=130s',
                'https://www.youtube.com/watch?v=60ItHLz5WEA&t=160s',
                'https://www.youtube.com/watch?v=60ItHLz5WEA&t=190s',
                'https://www.youtube.com/watch?v=60ItHLz5WEA&t=220s',
                'https://www.youtube.com/watch?v=60ItHLz5WEA&t=250s',
                'https://www.youtube.com/watch?v=60ItHLz5WEA&t=280s',
                'https://www.youtube.com/watch?v=60ItHLz5WEA&t=310s',
                'https://www.youtube.com/watch?v=60ItHLz5WEA&t=340s',
                'https://www.youtube.com/watch?v=60ItHLz5WEA&t=370s',
                'https://www.youtube.com/watch?v=60ItHLz5WEA&t=400s',
                'https://www.youtube.com/watch?v=60ItHLz5WEA&t=430s',
            ]),
        },
        {
            id: 'kiem-hiep-5',
            category: 'kiem-hiep',
            slug: 'kiem-hiep-5',
            title: 'Kiếm Hiệp 5',
            'ten-phim': 'Kiếm Hiệp 5',
            cover: '/film-posters/kiem-hiep/5.jpg',
            poster: '/film-posters/kiem-hiep/5.jpg',
            'mo-ta': 'Lời nguyền ngàn năm và chén thánh võ lâm.',
            description: 'Lời nguyền ngàn năm và chén thánh võ lâm.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Kiếm Hiệp'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=10s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=40s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=70s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=100s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=130s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=160s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=190s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=220s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=250s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=280s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=310s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=340s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=370s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=400s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=430s',
            ]),
        },
        {
            id: 'kiem-hiep-6',
            category: 'kiem-hiep',
            slug: 'kiem-hiep-6',
            title: 'Kiếm Hiệp 6',
            'ten-phim': 'Kiếm Hiệp 6',
            cover: '/film-posters/kiem-hiep/6.jpg',
            poster: '/film-posters/kiem-hiep/6.jpg',
            'mo-ta': 'Lời nguyền ngàn năm và chén thánh võ lâm.',
            description: 'Lời nguyền ngàn năm và chén thánh võ lâm.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Kiếm Hiệp'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=10s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=40s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=70s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=100s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=130s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=160s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=190s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=220s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=250s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=280s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=310s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=340s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=370s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=400s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=430s',
            ]),
        },
        {
            id: 'kiem-hiep-7',
            category: 'kiem-hiep',
            slug: 'kiem-hiep-7',
            title: 'Kiếm Hiệp 7',
            'ten-phim': 'Kiếm Hiệp 7',
            cover: '/film-posters/kiem-hiep/7.jpg',
            poster: '/film-posters/kiem-hiep/7.jpg',
            'mo-ta': 'Lời nguyền ngàn năm và chén thánh võ lâm.',
            description: 'Lời nguyền ngàn năm và chén thánh võ lâm.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Kiếm Hiệp'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=10s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=40s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=70s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=100s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=130s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=160s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=190s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=220s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=250s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=280s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=310s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=340s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=370s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=400s',
                'https://www.youtube.com/watch?v=YQHsXMglC9A&t=430s',
            ]),
        },
    ],

    // ---------------- XUYÊN KHÔNG ----------------
    'xuyen-khong': [
        {
            id: 'xuyen-khong-1',
            category: 'xuyen-khong',
            slug: 'xuyen-khong-1',
            title: 'Xuyên Không 1',
            'ten-phim': 'Xuyên Không 1',
            cover: '/film-posters/xuyen-khong/1.jpg',
            poster: '/film-posters/xuyen-khong/1.jpg',
            'mo-ta': 'Vô tình mở cổng dịch chuyển đến thế giới lạ.',
            description: 'Vô tình mở cổng dịch chuyển đến thế giới lạ.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Xuyên Không'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=9bZkp7q19f0&t=10s',
                'https://www.youtube.com/watch?v=9bZkp7q19f0&t=40s',
                'https://www.youtube.com/watch?v=9bZkp7q19f0&t=70s',
                'https://www.youtube.com/watch?v=9bZkp7q19f0&t=100s',
                'https://www.youtube.com/watch?v=9bZkp7q19f0&t=130s',
                'https://www.youtube.com/watch?v=9bZkp7q19f0&t=160s',
                'https://www.youtube.com/watch?v=9bZkp7q19f0&t=190s',
                'https://www.youtube.com/watch?v=9bZkp7q19f0&t=220s',
                'https://www.youtube.com/watch?v=9bZkp7q19f0&t=250s',
                'https://www.youtube.com/watch?v=9bZkp7q19f0&t=280s',
                'https://www.youtube.com/watch?v=9bZkp7q19f0&t=310s',
                'https://www.youtube.com/watch?v=9bZkp7q19f0&t=340s',
                'https://www.youtube.com/watch?v=9bZkp7q19f0&t=370s',
                'https://www.youtube.com/watch?v=9bZkp7q19f0&t=400s',
                'https://www.youtube.com/watch?v=9bZkp7q19f0&t=430s',
            ]),
        },
        {
            id: 'xuyen-khong-2',
            category: 'xuyen-khong',
            slug: 'xuyen-khong-2',
            title: 'Xuyên Không 2',
            'ten-phim': 'Xuyên Không 2',
            cover: '/film-posters/xuyen-khong/2.jpg',
            poster: '/film-posters/xuyen-khong/2.jpg',
            'mo-ta': 'Đến tương lai 1000 năm và gặp bản ngã khác.',
            description: 'Đến tương lai 1000 năm và gặp bản ngã khác.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Xuyên Không'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=6Dh-RL__uN4&t=10s',
                'https://www.youtube.com/watch?v=6Dh-RL__uN4&t=40s',
                'https://www.youtube.com/watch?v=6Dh-RL__uN4&t=70s',
                'https://www.youtube.com/watch?v=6Dh-RL__uN4&t=100s',
                'https://www.youtube.com/watch?v=6Dh-RL__uN4&t=130s',
                'https://www.youtube.com/watch?v=6Dh-RL__uN4&t=160s',
                'https://www.youtube.com/watch?v=6Dh-RL__uN4&t=190s',
                'https://www.youtube.com/watch?v=6Dh-RL__uN4&t=220s',
                'https://www.youtube.com/watch?v=6Dh-RL__uN4&t=250s',
                'https://www.youtube.com/watch?v=6Dh-RL__uN4&t=280s',
                'https://www.youtube.com/watch?v=6Dh-RL__uN4&t=310s',
                'https://www.youtube.com/watch?v=6Dh-RL__uN4&t=340s',
                'https://www.youtube.com/watch?v=6Dh-RL__uN4&t=370s',
                'https://www.youtube.com/watch?v=6Dh-RL__uN4&t=400s',
                'https://www.youtube.com/watch?v=6Dh-RL__uN4&t=430s',
            ]),
        },
        {
            id: 'xuyen-khong-3',
            category: 'xuyen-khong',
            slug: 'xuyen-khong-3',
            title: 'Xuyên Không 3',
            'ten-phim': 'Xuyên Không 3',
            cover: '/film-posters/xuyen-khong/3.jpg',
            poster: '/film-posters/xuyen-khong/3.jpg',
            'mo-ta': 'Va vào đa vũ trụ, mỗi quyết định mở ra một chiều không gian khác.',
            description: 'Va vào đa vũ trụ, mỗi quyết định mở ra một chiều không gian khác.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Xuyên Không'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=JGwWNGJdvx8&t=10s',
                'https://www.youtube.com/watch?v=JGwWNGJdvx8&t=40s',
                'https://www.youtube.com/watch?v=JGwWNGJdvx8&t=70s',
                'https://www.youtube.com/watch?v=JGwWNGJdvx8&t=100s',
                'https://www.youtube.com/watch?v=JGwWNGJdvx8&t=130s',
                'https://www.youtube.com/watch?v=JGwWNGJdvx8&t=160s',
                'https://www.youtube.com/watch?v=JGwWNGJdvx8&t=190s',
                'https://www.youtube.com/watch?v=JGwWNGJdvx8&t=220s',
                'https://www.youtube.com/watch?v=JGwWNGJdvx8&t=250s',
                'https://www.youtube.com/watch?v=JGwWNGJdvx8&t=280s',
                'https://www.youtube.com/watch?v=JGwWNGJdvx8&t=310s',
                'https://www.youtube.com/watch?v=JGwWNGJdvx8&t=340s',
                'https://www.youtube.com/watch?v=JGwWNGJdvx8&t=370s',
                'https://www.youtube.com/watch?v=JGwWNGJdvx8&t=400s',
                'https://www.youtube.com/watch?v=JGwWNGJdvx8&t=430s',
            ]),
        },
        {
            id: 'xuyen-khong-4',
            category: 'xuyen-khong',
            slug: 'xuyen-khong-4',
            title: 'Xuyên Không 4',
            'ten-phim': 'Xuyên Không 4',
            cover: '/film-posters/xuyen-khong/4.jpg',
            poster: '/film-posters/xuyen-khong/4.jpg',
            'mo-ta': 'Quay ngược thời gian để cứu thế giới khỏi đại dịch.',
            description: 'Quay ngược thời gian để cứu thế giới khỏi đại dịch.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Xuyên Không'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=euCqAq6BRa4&t=10s',
                'https://www.youtube.com/watch?v=euCqAq6BRa4&t=40s',
                'https://www.youtube.com/watch?v=euCqAq6BRa4&t=70s',
                'https://www.youtube.com/watch?v=euCqAq6BRa4&t=100s',
                'https://www.youtube.com/watch?v=euCqAq6BRa4&t=130s',
                'https://www.youtube.com/watch?v=euCqAq6BRa4&t=160s',
                'https://www.youtube.com/watch?v=euCqAq6BRa4&t=190s',
                'https://www.youtube.com/watch?v=euCqAq6BRa4&t=220s',
                'https://www.youtube.com/watch?v=euCqAq6BRa4&t=250s',
                'https://www.youtube.com/watch?v=euCqAq6BRa4&t=280s',
                'https://www.youtube.com/watch?v=euCqAq6BRa4&t=310s',
                'https://www.youtube.com/watch?v=euCqAq6BRa4&t=340s',
                'https://www.youtube.com/watch?v=euCqAq6BRa4&t=370s',
                'https://www.youtube.com/watch?v=euCqAq6BRa4&t=400s',
                'https://www.youtube.com/watch?v=euCqAq6BRa4&t=430s',
            ]),
        },
        {
            id: 'xuyen-khong-5',
            category: 'xuyen-khong',
            slug: 'xuyen-khong-5',
            title: 'Xuyên Không 5',
            'ten-phim': 'Xuyên Không 5',
            cover: '/film-posters/xuyen-khong/5.jpg',
            poster: '/film-posters/xuyen-khong/5.jpg',
            'mo-ta': 'Sai lệch thời gian tạo ra nghịch lý nguy hiểm.',
            description: 'Sai lệch thời gian tạo ra nghịch lý nguy hiểm.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Xuyên Không'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=10s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=40s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=70s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=100s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=130s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=160s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=190s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=220s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=250s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=280s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=310s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=340s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=370s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=400s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=430s',
            ]),
        },
        {
            id: 'xuyen-khong-6',
            category: 'xuyen-khong',
            slug: 'xuyen-khong-6',
            title: 'Xuyên Không 6',
            'ten-phim': 'Xuyên Không 6',
            cover: '/film-posters/xuyen-khong/6.jpg',
            poster: '/film-posters/xuyen-khong/6.jpg',
            'mo-ta': 'Sai lệch thời gian tạo ra nghịch lý nguy hiểm.',
            description: 'Sai lệch thời gian tạo ra nghịch lý nguy hiểm.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Xuyên Không'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=10s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=40s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=70s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=100s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=130s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=160s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=190s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=220s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=250s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=280s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=310s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=340s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=370s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=400s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=430s',
            ]),
        },
        {
            id: 'xuyen-khong-7',
            category: 'xuyen-khong',
            slug: 'xuyen-khong-7',
            title: 'Xuyên Không 7',
            'ten-phim': 'Xuyên Không 7',
            cover: '/film-posters/xuyen-khong/7.jpg',
            poster: '/film-posters/xuyen-khong/7.jpg',
            'mo-ta': 'Sai lệch thời gian tạo ra nghịch lý nguy hiểm.',
            description: 'Sai lệch thời gian tạo ra nghịch lý nguy hiểm.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Xuyên Không'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=10s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=40s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=70s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=100s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=130s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=160s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=190s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=220s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=250s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=280s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=310s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=340s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=370s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=400s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=430s',
            ]),
        },
        {
            id: 'xuyen-khong-8',
            category: 'xuyen-khong',
            slug: 'xuyen-khong-8',
            title: 'Xuyên Không 8',
            'ten-phim': 'Xuyên Không 8',
            cover: '/film-posters/xuyen-khong/8.jpg',
            poster: '/film-posters/xuyen-khong/8.jpg',
            'mo-ta': 'Sai lệch thời gian tạo ra nghịch lý nguy hiểm.',
            description: 'Sai lệch thời gian tạo ra nghịch lý nguy hiểm.',
            'so-tap': 15,
            duration: '20 phút',
            tags: ['Xuyên Không'],
            episodes: mapEpisodes([
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=10s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=40s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=70s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=100s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=130s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=160s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=190s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=220s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=250s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=280s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=310s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=340s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=370s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=400s',
                'https://www.youtube.com/watch?v=RubBzkZzpUA&t=430s',
            ]),
        },
    ],
};
